<a href="https://colab.research.google.com/github/vivianagonzalez203/Bootcamp-Data-Science/blob/main/02_Python/Clase_07_Introducci%C3%B3n_a_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 5: Introducción a Pandas

https://pandas.pydata.org/docs/index.html



---


## Qué es Pandas?

- Biblioteca de Python para manipulación y análisis de datos

- Trabaja con estructuras de datos tipo tablas (DataFrames)

- Ideal para trabajar con datos estructurados (CSV, Excel, SQL, etc)

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Si es necesario instalar
# !pip install pandas

import pandas as pd
print(f"Versión de Pandas: {pd.__version__}")

Versión de Pandas: 2.2.2

### Conceptos Clave:

- Series: Arreglo unidimensional etiquetado

- DataFrame: Estructura bidimensional tipo tabla

- Índices: Etiquetas para acceder a los datos

## Series vs Dataframe

In [ ]:
# Una serie es una columna

edades = pd.Series([20,25,30])

edades

0    20
1    25
2    30
dtype: int64

In [ ]:
# Un Dataframe es una tabla

datos = {
    "Nombre":["Ana","Luis","Pedro"],
    "Edad":[20,25,30],
    "Ciudad":["Bogotá","Pereira","Cali"]
}

df = pd.DataFrame(datos)

df

  Nombre  Edad   Ciudad
0    Ana    20   Bogotá
1   Luis    25  Pereira
2  Pedro    30     Cali

## Leer archivos

In [ ]:
# Subir el archivo desde tu computador
from google.colab import files
uploaded = files.upload()

Saving Ventastaller..xlsx to Ventastaller..xlsx
Saving Clientes.xlsx to Clientes (5).xlsx

In [ ]:
clientes = pd.read_excel("Clientes (5).xlsx")

In [ ]:
ventas = pd.read_excel("Ventastaller..xlsx")

In [ ]:
clientes.head() # Muestra las primeras 5 filas

  id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium

In [ ]:
clientes.tail() # Muestra las ultimas filas

  id_cliente nombre_cliente     ciudad segmento
5        C06    Juan Castro   Medellín  Regular
6        C07  Valentina Gil     Bogotá  Premium
7        C08   Andrés Mejía    Armenia  Regular
8        C09    Laura Rojas    Pereira  Premium
9        C10  Daniel Vargas  Manizales  Regular

## Conociendo el Dataset

In [ ]:
clientes.shape # Tamaño

(10, 4)

In [ ]:
clientes.columns # Nombres de columnas

Index(['id_cliente', 'nombre_cliente', 'ciudad', 'segmento'], dtype='object')

In [ ]:
clientes.info() # Información general

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      10 non-null     object
 1   nombre_cliente  10 non-null     object
 2   ciudad          10 non-null     object
 3   segmento        10 non-null     object
dtypes: object(4)
memory usage: 452.0+ bytes

In [ ]:
ventas.describe() # Estadísticas

                               Fecha   Cantidad  Precio_Unitario
count                             51  49.000000     5.100000e+01
mean   2026-01-25 03:17:38.823529472   2.959184     1.030196e+06
min              2026-01-01 00:00:00   1.000000     8.500000e+04
25%              2026-01-12 12:00:00   1.000000     1.200000e+05
50%              2026-01-25 00:00:00   2.000000     8.500000e+05
75%              2026-02-06 12:00:00   4.000000     2.500000e+06
max              2026-02-19 00:00:00  10.000000     2.500000e+06
std                              NaN   2.449143     1.046791e+06

In [ ]:
clientes.dtypes #Tipo de dato

id_cliente        object
nombre_cliente    object
ciudad            object
segmento          object
dtype: object

In [ ]:
clientes.sample(5) # Muestra datos al azar

  id_cliente nombre_cliente    ciudad segmento
7        C08   Andrés Mejía   Armenia  Regular
2        C03    María López   Armenia  Premium
8        C09    Laura Rojas   Pereira  Premium
5        C06    Juan Castro  Medellín  Regular
4        C05  Sofía Herrera      Cali  Premium

## Seleccionar datos

In [ ]:
clientes["ciudad"]

0      Pereira
1    Manizales
2      Armenia
3      Pereira
4         Cali
5     Medellín
6       Bogotá
7      Armenia
8      Pereira
9    Manizales
Name: ciudad, dtype: object

In [ ]:
clientes[["nombre_cliente","ciudad"]]

  nombre_cliente     ciudad
0     Ana Torres    Pereira
1     Luis Gómez  Manizales
2    María López    Armenia
3    Carlos Ruiz    Pereira
4  Sofía Herrera       Cali
5    Juan Castro   Medellín
6  Valentina Gil     Bogotá
7   Andrés Mejía    Armenia
8    Laura Rojas    Pereira
9  Daniel Vargas  Manizales

In [ ]:
# Filas

clientes.iloc[6]

id_cliente                  C07
nombre_cliente    Valentina Gil
ciudad                   Bogotá
segmento                Premium
Name: 6, dtype: object

In [ ]:
clientes.iloc[0:5]

  id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium

## Filtrar información

In [ ]:
# Clientes de Pereira

clientes[clientes["ciudad"] == "Pereira"]

  id_cliente nombre_cliente   ciudad segmento
0        C01     Ana Torres  Pereira  Premium
3        C04    Carlos Ruiz  Pereira  Regular
8        C09    Laura Rojas  Pereira  Premium

In [ ]:
clientes[clientes['nombre_cliente'].str.startswith("Lu")] # Startswith - Empezar con

  id_cliente nombre_cliente     ciudad segmento
1        C02     Luis Gómez  Manizales  Regular

In [ ]:
clientes[clientes['nombre_cliente'].str.contains("an")] # Contains - contiene

  id_cliente nombre_cliente     ciudad segmento
5        C06    Juan Castro   Medellín  Regular
9        C10  Daniel Vargas  Manizales  Regular

In [ ]:
clientes[clientes['nombre_cliente'].str.endswith("ez")] # Endswith - Termine en

  id_cliente nombre_cliente     ciudad segmento
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium

In [ ]:
# Dos condiciones
clientes[
    (clientes["segmento"]== "Regular") & # & and-y
    (clientes["ciudad"]=="Manizales") | # | or-o
    (clientes["nombre_cliente"].str.startswith("Lu"))
]

  id_cliente nombre_cliente     ciudad segmento
1        C02     Luis Gómez  Manizales  Regular

In [ ]:
clientes_filtrados = [nombre_cliente for nombre_cliente in clientes["nombre_cliente"]
                      if "Daniel" in nombre_cliente]

clientes_filtrados

['Daniel Vargas']

## Crear columnas nuevas

In [ ]:
ventas["IVA"] = ventas["Precio_Unitario"]*0.19

In [ ]:
ventas.head()

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,IVA
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado,16150.0
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO,22800.0
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente,161500.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0

## Mini reto

Usa la base de datos de ventas y responde


Preguntas:

* Mostrar las primeras 10 filas.
* Cuántas filas tiene?
* Mostrar solo las columnas:
  * Producto
  * Precio
* Mostrar únicamente productos mayores a $100.000.
* Crear una columna Precio Final.
* Mostrar únicamente productos de laptop.